mvn exec:java -Dexec.args="MutableAVL insert UNSORTED"
mvn exec:java -Dexec.args="MutableAVL insert SORTEDASC"
mvn exec:java -Dexec.args="MutableAVL insert SORTEDESC"
mvn exec:java -Dexec.args="ImmutableAVL insert UNSORTED"
mvn exec:java -Dexec.args="ImmutableAVL insert SORTEDASC"
mvn exec:java -Dexec.args="ImmutableAVL insert SORTEDESC"